yatube/about/urls.py
"""about URL Configuration"""

from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
"""posts URL Configuration"""

from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
"""yatube URL Configuration"""

from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("posts:group_list", kwargs={"slug": self.slug})


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ['-pub_date']
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментатор'
    )
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments'
    )

    class Meta:
        ordering = ['-created']


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=['user', 'author'],
                name='unique_following'
            )
        ]

yatube/posts/forms.py
from django.forms import ModelForm, Select, Textarea

from .models import Comment, Post


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')

        widgets = {
            "text": Textarea(attrs={
                'class': 'form-control',
                'cols': '40',
                'rows': '10'
            }),
            "group": Select(attrs={'class': 'form-control'})
        }

        labels = {
            'text': 'Текст нового поста',
            'group': 'Группа, к которой будет относиться пост',
        }


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            "text": Textarea(attrs={
                'class': 'form-control',
                'cols': '40',
                'rows': '10'
            }),
        }

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User
from .utils import paginator_obj


def index(request):
    posts = Post.objects.all()
    page_obj = paginator_obj(request, posts)
    return render(request, 'posts/index.html', {'page_obj': page_obj})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = paginator_obj(request, posts)
    context = {
        'page_obj': page_obj,
        'group': group,
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    posts = user.posts.all()
    page_obj = paginator_obj(request, posts)
    count_posts = posts.count()
    following = False
    # просто поменять местами чтобы работало... рукалицо...
    # теперь буду знать, и логика в этом есть. спасибо, Саид)))
    following = (request.user.is_authenticated and Follow.objects.filter(
        user=request.user,
        author=user).exists()
    )
    context = {
        'username': user,
        'page_obj': page_obj,
        'count_posts': count_posts,
        'following': following,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    author = post.author
    count_posts = author.posts.count()
    comments = post.comments.all()
    context = {
        'post': post,
        'author': author,
        'count_posts': count_posts,
        'comments': comments,
        'form': CommentForm(),
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form = form.save(commit=False)
        form.author = request.user
        form.save()
        return redirect('posts:profile', username=request.user.username)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.user != post.author:
        return redirect('posts:post_detail', post_id=post_id)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    page_obj = paginator_obj(request, posts)
    return render(request, 'posts/follow.html', {'page_obj': page_obj})


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}

{% block title %}
  {% if is_edit %}
  Редактировать запись
  {% else %}
  Новый пост
  {% endif %}
{% endblock %}

{% block content %}
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">  
                {% if is_edit %}
                  Редактирование поста
                {% else %}
                  Новый пост
                {% endif %}                        
              </div>
              <div class="card-body">        
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form }}                 
                    </label>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Избранные авторы{% endblock %}

{% block content %} 
{% include 'posts/includes/switcher.html' %}
  <h1>Лента избранных авторов</h1>

  {% for post in page_obj %} 
    <article> 
      <ul> 
        <li> 
          Автор: {{ post.author.get_full_name }} 
        </li> 
        <li> 
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li> 
      </ul> 
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:post_detail' post.id %}">Подробнее</a>
      <br>
      {% if post.group %}
        <a href="{{ post.group.get_absolute_url }}">все записи группы {{ post.group }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %} 
    </article> 
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}
    
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Записи сообщества {{ group }}{% endblock %}

{% block content %}
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  
  {% for post in page_obj %}
    <article>
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text }}</p>
      {% if not forloop.last %}<hr>{% endif %}    
    </article>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
  <a href="{% url 'posts:index' %}">на главную</a>
{% endblock %}    

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% load thumbnail %}
{% load cache %}

{% block title %}Это главная страница проекта Yatube{% endblock %}

{% block content %}
{% include 'posts/includes/switcher.html' %}
  <h1>Последние обновления на сайте</h1>

  {% cache 20 index_page %}
  {% for post in page_obj %} 
    <article> 
      <ul> 
        <li> 
          Автор: {{ post.author.get_full_name }} 
        </li> 
        <li> 
          Дата публикации: {{ post.pub_date|date:"d E Y" }} 
        </li> 
      </ul> 
      {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}
      <p>{{ post.text|truncatechars:500 }}</p>
      <a href="{% url 'posts:post_detail' post.pk %}">читать дальше</a>
      <br>
      {% if post.group %}
        <a href="{{ post.group.get_absolute_url }}">все записи группы {{ post.group }}</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %} 
    </article> 
  {% endfor %}
  {% endcache %} 

  {% include 'posts/includes/paginator.html' %}
    
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Пост {{ post.text|truncatechars:30 }}{% endblock %}

{% block content %}

      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
            <!-- если у поста есть группа -->
              {% if post.group %}
              <li class="list-group-item">
                Группа: {{post.group}}
                <a href="{{post.group.get_absolute_url}}">все записи группы</a>
              </li>
              {% endif %}
              <li class="list-group-item">
                Автор: {{ post.author.get_full_name }}
              </li>
              <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ count_posts }}</span>
            </li>
            <li class="list-group-item">
              <a href="{{post.user.get_absolute_url}}">все посты пользователя</a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
        </article>
        {% if post.author == request.user %}
          <button type="submit" class="btn btn-primary">
          <a class="btn btn-primary" href="{% url 'posts:post_edit' post_id=post.id %}">
            редактировать запись
          </a>
          </button>
        {% endif %}

        {% include 'posts/includes/comments.html' %}

      </div> 

{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block title %}Профайл пользователя {{ username }}{% endblock %}

{% block content %}
      <div class="container py-5">        
        <h1>Все посты пользователя {{ username }}</h1>
        <h3>Всего постов: {{ count_posts }}</h3>

        {% if request.user != username %}
          {% if following %}
            <a
              class="btn btn-lg btn-light"
              href="{% url 'posts:profile_unfollow' username %}" role="button"
            >
              Отписаться
            </a>
          {% else %}
            <a
              class="btn btn-lg btn-primary"
              href="{% url 'posts:profile_follow' username %}" role="button"
            >
              Подписаться
            </a>
          {% endif %}
        {% endif %}

        {% for post in page_obj %}   
        <article>
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
              <a href="{{ post.user.get_absolute_url }}">все посты пользователя</a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }} 
            </li>
          </ul>
          {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
          <img class="card-img my-2" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
          <br>
          {% if post.group %}
            <a href="{{ post.group.get_absolute_url }}">все записи группы {{post.group}}</a>
          {% endif %}
          {% if not forloop.last %}<hr>{% endif %} 
        </article>
        {% endfor %}

        {% include 'posts/includes/paginator.html' %}
      </div>
{% endblock %}